

class RandomGenerator{
	constructor(min, max){ 
		//takes in the minimum and maximum values
		this.min = min;
		this.max = max;
		if(!this.min && !this.max){
			this.min = 1;
			this.max = 10;	
		}
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
		this.randomNumber = 0;
	}
	generate(){
		//make a random value between the minimum and maximum values
		this.randomNumber = Math.floor(Math.random() * this.max+1 ) + this.min;
		//and store the number into the storage from the constructor
	}
	getRange(){
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		return {'min': this.min, 'max': this.max};
		//returns a basic object literal
	}
	getNum(){
		//return the random number that was generated by generate()
		return this.randomNumber;
	}
}